### ISSUE TITLE
private publish must have self as recipient

### ISSUE THREAD

**Issue by ameba23** [ssbc/scuttle-invite#1]
invites.async.private.publish breaks when you do not include yourself as a recipient, as it cannot decrypt the message to include it in the callback.  

although i cant think why you wouldnt want to have yourself as an extra recipient, it would be nice if it failed gracefully with an error message (as i spent ages trying to work out what was going wrong).

**Comment by m4gpi** [comment]
To resolve this, I'll interpolate `server.id` directly into the params, that way you're always a recipient of the invite. No point in raising an error when you can simply add yourself in.
